export const getUsers = async (req, res) => {
  try {
  } catch (error) {
    console.log(error);
    res.s;
  }
};
